### ISSUE TITLE
Github module to add/remove users from organizations

### ISSUE THREAD

**Issue by jvehent** [mozilla-services/userplex#2]
There's a great [Go module](https://github.com/google/go-github) for Github.

**Comment by jvehent** [comment]
@milescrabill : So, what's the state of this?

**Comment by milescrabill** [comment]
It works and is merged. The config file is in the secrets repo and works as expected (removes users, does not add). The current state of mozilla-services repo does _not_ match the intended state due to certain users not having 2FA or not being in the proper LDAP groups.

I improved the UX / output in https://github.com/mozilla-services/userplex/pull/37.

**Comment by milescrabill** [comment]
The output continues to be improved, and as of https://github.com/mozilla-services/userplex/pull/41 it pulls Github usernames from LDAP. I think this is closeable.
